mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^problems/', include('problems.urls', namespace="problems")),
    url(r'^admin/', include(admin.site.urls)),
)

problems/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView, ListView
from django.utils import timezone
from problems.models import Problem

urlpatterns = patterns('',
	# ex: /problems/
	url(r'^$',
		ListView.as_view(
			queryset=Problem.objects.filter(create_date__lte=timezone.now) \
				.order_by('-create_date')[:5],
			context_object_name='latest_problem_list',
			template_name='problems/index.html'),
		name='index'),
	# ex: /problems/5/
	url(r'^(?P<pk>\d+)/$',
		DetailView.as_view(
			queryset=Problem.objects.filter(create_date__lte=timezone.now),
			model=Problem,
			template_name='problems/detail.html'),
		name='detail'),
	# ex: /problems/5/results/
	url(r'^(?P<pk>\d+)/results/$',
		DetailView.as_view(
			model=Problem,
			template_name='problems/results.html'),
		name='results'),
	# ex: /problems/5/vote/
	url(r'^(?P<problem_id>\d+)/vote/$', 'problems.views.vote', name='vote'),
)

problems/models.py
import datetime
from django.db import models
from django.utils import timezone


class Problem(models.Model):
        question = models.CharField(max_length=200)
        create_date = models.DateTimeField('date created')

        def was_created_recently(self):
            now = timezone.now()
            return now - datetime.timedelta(days=1) <= self.create_date < now
        was_created_recently.admin_order_field = 'create_date'
        was_created_recently.boolean = True
        was_created_recently.short_description = 'Created recently?'

        def __unicode__(self):
                return self.question

class Choice(models.Model):
        problem = models.ForeignKey(Problem)
        choice_text = models.CharField(max_length=200)
        votes = models.IntegerField(default=0)

        def __unicode__(self):
                return self.choice_text

problems/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from problems.models import Problem, Choice


def vote(request, problem_id):
        p = get_object_or_404(Problem, pk=problem_id)
        try:
                selected_choice = p.choice_set.get(pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
                # Redisplay the problem voting form.
                return render(request, 'problems/detail.html', {
                        'problem': p,
                        'error_message': "You didn't select a choice.",
                })
        else:
                selected_choice.votes += 1
                selected_choice.save()
                # Always return an HttpResponseRedirect after successfully dealing
                # with POST data. This prevents data from being posted twice if a
                # user hits the Back button.
                return HttpResponseRedirect(reverse('problems:results', args=(p.id,)))

problems/templates/problems/detail.html
<h1>{{ problem.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif%}

<form action="{% url 'problems:vote' problem.id %}" method="post">
{% csrf_token %}
{% for choice in problem.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
	<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

problems/templates/problems/index.html
{% if latest_problem_list %}
	<ul>
	{% for problem in latest_problem_list %}
		<li><a href="{% url 'problems:detail' problem.id %}">{{ problem.question|slice:":50"|add:"..." }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No problems are available.</p>
{% endif %}

problems/templates/problems/results.html
<h1>{{ problem.question }}</h1>

<ul>
{% for choice in problem.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'problems:detail' problem.id %}">Vote again?</a>